name: CI Build

on:
   push:
      branches:
      - '*'
   pull_request:
      branches:
      - '*'
env:
   LC_ALL: en_US.UTF-8
   GRADLE_OPTS: >-
      -Dorg.gradle.parallel=true

defaults:
   run:
      shell: bash

jobs:
   build:
      name: Gradle Build
      runs-on: ubuntu-latest
      steps:
      -  name: Git Checkout
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
      -  name: Gradle Wrapper Validation
         uses: gradle/actions/wrapper-validation@v4
      -  name: Set up JDK 21
         uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
         with:
            distribution: temurin
            cache: gradle
            java-version: 21
      -  name: Set up Docker
         run: |
            docker info
      -  name: Grant execute permission for gradlew
         run: chmod +x ./gradlew
      -  name: Gradle version
         run: ./gradlew --no-daemon --version
      -  name: Build with Gradle
         run: ./gradlew build --info
      -  name: Upload JAR Files
         uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
         with:
            name: jar-files
            path: |
               **/generated/*.jar
      -  name: Upload Test Reports
         if: always()
         uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
         with:
            name: Test-reports
            path: |
               **/test-reports/*/TEST-*.xml

   container_deploy:
      name: Container Deploy
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      needs: build
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
      steps:
      -  name: Checkout code
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
      -  name: Download model atlas artifacts
         uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
         with:
            name: jar-files
            path: .
      -  name: Update dockerhub repo description
         uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4.0.2
         with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_API_TOKEN }}
            repository: eclipsefennec/model.atlas
            readme-filepath: ./docker/modelatlas/README.md

      -  name: Set up Docker Buildx
         uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      -  name: Login to Docker Hub
         uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
         with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_API_TOKEN }}
      -  name: Login to Github Docker Registry
         uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
         with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      -  name: Build and Push Multi-Arch Docker Image
         uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
         with:
            context: .
            file: docker/modelatlas/Dockerfile
            platforms: linux/amd64,linux/arm64/v8
            push: true
            tags: |-
               docker.io/eclipsefennec/model.atlas:snapshot
               ghcr.io/eclipsefennec/model.atlas:snapshot